// Auto-generated by build.js — do not edit
  const receipts = [
  {
    "id": "hh_1748",
    "kind": "transaction",
    "source": "household",
    "title": "Other",
    "when": "2016-12-10T18:30:00.000Z",
    "place": "Cash",
    "people": [
      "Household"
    ],
    "body": "jeevan drop — 45 INR (Expense)",
    "category": "Other",
    "subcategory": ""
  },
  {
    "id": "hh_1754",
    "kind": "transaction",
    "source": "household",
    "title": "Mobile Service Provider",
    "when": "2016-12-08T18:30:00.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "Mobile Service Provider recharge wfh — 301 INR (Expense)",
    "category": "subscription",
    "subcategory": "Mobile Service Provider"
  },
  {
    "id": "hh_1755",
    "kind": "transaction",
    "source": "household",
    "title": "Grocery",
    "when": "2016-12-07T18:30:00.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "cheese cubes(2) — 30 INR (Expense)",
    "category": "Food",
    "subcategory": "Grocery"
  },
  {
    "id": "hh_1783",
    "kind": "transaction",
    "source": "household",
    "title": "Ice cream",
    "when": "2016-11-28T00:47:10.000Z",
    "place": "Cash",
    "people": [
      "Household"
    ],
    "body": "mava 1 large — 20 INR (Expense)",
    "category": "Food",
    "subcategory": "Ice cream"
  },
  {
    "id": "hh_1860",
    "kind": "transaction",
    "source": "household",
    "title": "grooming",
    "when": "2016-10-07T18:30:00.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "razor — 174 INR (Expense)",
    "category": "Beauty",
    "subcategory": "grooming"
  },
  {
    "id": "hh_1869",
    "kind": "transaction",
    "source": "household",
    "title": "Other",
    "when": "2016-09-28T02:02:36.000Z",
    "place": "Cash",
    "people": [
      "Household"
    ],
    "body": "flour mill — 32 INR (Expense)",
    "category": "Other",
    "subcategory": ""
  },
  {
    "id": "hh_1885",
    "kind": "transaction",
    "source": "household",
    "title": "beverage",
    "when": "2016-09-07T18:30:00.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "cold coffee — 30 INR (Expense)",
    "category": "Food",
    "subcategory": "beverage"
  },
  {
    "id": "hh_1891",
    "kind": "transaction",
    "source": "household",
    "title": "RD",
    "when": "2016-09-04T18:30:00.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "(no note) — 1000 INR (Expense)",
    "category": "Investment",
    "subcategory": "RD"
  },
  {
    "id": "hh_1898",
    "kind": "transaction",
    "source": "household",
    "title": "Ganesh Pujan",
    "when": "2016-08-29T06:11:25.000Z",
    "place": "Cash",
    "people": [
      "Household"
    ],
    "body": "Ganesh idol — 361 INR (Expense)",
    "category": "Festivals",
    "subcategory": "Ganesh Pujan"
  },
  {
    "id": "hh_1900",
    "kind": "transaction",
    "source": "household",
    "title": "Toiletries",
    "when": "2016-08-29T05:18:20.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "lizol — 98 INR (Expense)",
    "category": "Household",
    "subcategory": "Toiletries"
  },
  {
    "id": "hh_1901",
    "kind": "transaction",
    "source": "household",
    "title": "Rakshabandhan",
    "when": "2016-08-24T02:08:04.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "rakshabandhan ovalni  — 500 INR (Expense)",
    "category": "Festivals",
    "subcategory": "Rakshabandhan"
  },
  {
    "id": "hh_1914",
    "kind": "transaction",
    "source": "household",
    "title": "RD",
    "when": "2016-08-04T18:30:00.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "(no note) — 1000 INR (Expense)",
    "category": "Investment",
    "subcategory": "RD"
  },
  {
    "id": "hh_1916",
    "kind": "transaction",
    "source": "household",
    "title": "misc",
    "when": "2016-08-03T18:30:00.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "ipad cover — 260 INR (Expense)",
    "category": "Family",
    "subcategory": "misc"
  },
  {
    "id": "hh_1927",
    "kind": "transaction",
    "source": "household",
    "title": "Mutual fund",
    "when": "2016-07-06T18:30:00.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "Mutual fund B — 1000 INR (Expense)",
    "category": "Investment",
    "subcategory": "Mutual fund"
  },
  {
    "id": "hh_1946",
    "kind": "transaction",
    "source": "household",
    "title": "Eggs",
    "when": "2016-06-11T18:30:00.000Z",
    "place": "Cash",
    "people": [
      "Household"
    ],
    "body": "(no note) — 84 INR (Expense)",
    "category": "Food",
    "subcategory": "Eggs"
  },
  {
    "id": "hh_1950",
    "kind": "transaction",
    "source": "household",
    "title": "Mutual fund",
    "when": "2016-06-06T18:30:00.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "Mutual fund B — 1000 INR (Expense)",
    "category": "Investment",
    "subcategory": "Mutual fund"
  },
  {
    "id": "hh_2118",
    "kind": "transaction",
    "source": "household",
    "title": "auto",
    "when": "2015-10-31T03:56:37.000Z",
    "place": "Cash",
    "people": [
      "Household"
    ],
    "body": "golden circle to b45 — 180 INR (Expense)",
    "category": "Transportation",
    "subcategory": "auto"
  },
  {
    "id": "hh_2122",
    "kind": "transaction",
    "source": "household",
    "title": "Gift",
    "when": "2015-10-28T16:08:44.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "to Family — 1000 INR (Expense)",
    "category": "Gift",
    "subcategory": ""
  },
  {
    "id": "hh_2123",
    "kind": "transaction",
    "source": "household",
    "title": "Bus",
    "when": "2015-10-28T15:58:33.000Z",
    "place": "Cash",
    "people": [
      "Household"
    ],
    "body": "Place 2 to brc travels — 660 INR (Expense)",
    "category": "Transportation",
    "subcategory": "Bus"
  },
  {
    "id": "hh_2148",
    "kind": "transaction",
    "source": "household",
    "title": "Other",
    "when": "2015-09-26T02:54:14.000Z",
    "place": "Cash",
    "people": [
      "Household"
    ],
    "body": "shoe polish — 30 INR (Expense)",
    "category": "Other",
    "subcategory": ""
  },
  {
    "id": "hh_2162",
    "kind": "transaction",
    "source": "household",
    "title": "Other",
    "when": "2015-08-28T04:08:54.000Z",
    "place": "Saving Bank account 1",
    "people": [
      "Household"
    ],
    "body": "audible subscription — 199 INR (Expense)",
    "category": "Other",
    "subcategory": ""
  },
  {
    "id": "sp_3003",
    "kind": "music",
    "source": "spotify",
    "title": "Downtown (feat. Melle Mel, Grandmaster Caz, Kool Moe Dee & Eric Nally)",
    "when": "2015-08-28T01:51:19.000Z",
    "place": "android",
    "people": [],
    "body": "Macklemore & Ryan Lewis — Downtown (feat. Melle Mel, Grandmaster Caz, Kool Moe Dee & Eric Nally) (110s)",
    "artist": "Macklemore & Ryan Lewis",
    "album": "Downtown (feat. Melle Mel, Grandmaster Caz, Kool Moe Dee & Eric Nally)"
  },
  {
    "id": "sp_3005",
    "kind": "music",
    "source": "spotify",
    "title": "Cinemetropolis",
    "when": "2015-08-28T01:55:16.000Z",
    "place": "android",
    "people": [],
    "body": "Blue Scholars — Cinemetropolis (184s)",
    "artist": "Blue Scholars",
    "album": "Cinemetropolis"
  },
  {
    "id": "sp_3006",
    "kind": "music",
    "source": "spotify",
    "title": "No Rest For The Weary",
    "when": "2015-08-28T01:57:00.000Z",
    "place": "android",
    "people": [],
    "body": "Blue Scholars — Blue Scholars (69s)",
    "artist": "Blue Scholars",
    "album": "Blue Scholars"
  },
  {
    "id": "sp_3008",
    "kind": "music",
    "source": "spotify",
    "title": "Are You With Me - Radio Edit",
    "when": "2015-08-28T03:16:45.000Z",
    "place": "android",
    "people": [],
    "body": "Lost Frequencies — Are You With Me (175s)",
    "artist": "Lost Frequencies",
    "album": "Are You With Me"
  },
  {
    "id": "sp_3009",
    "kind": "music",
    "source": "spotify",
    "title": "Hey Mama (feat. Nicki Minaj, Bebe Rexha & Afrojack)",
    "when": "2015-08-28T03:19:57.000Z",
    "place": "android",
    "people": [],
    "body": "David Guetta — Listen (193s)",
    "artist": "David Guetta",
    "album": "Listen"
  },
  {
    "id": "sp_3397",
    "kind": "music",
    "source": "spotify",
    "title": "Drag Me Down",
    "when": "2015-09-26T02:43:04.000Z",
    "place": "android",
    "people": [],
    "body": "One Direction — Drag Me Down (191s)",
    "artist": "One Direction",
    "album": "Drag Me Down"
  },
  {
    "id": "sp_3398",
    "kind": "music",
    "source": "spotify",
    "title": "Let Her Go",
    "when": "2015-09-26T02:45:24.000Z",
    "place": "android",
    "people": [],
    "body": "Passenger — All the Little Lights (36s)",
    "artist": "Passenger",
    "album": "All the Little Lights"
  },
  {
    "id": "sp_3400",
    "kind": "music",
    "source": "spotify",
    "title": "Paraíso",
    "when": "2015-09-26T02:49:17.000Z",
    "place": "android",
    "people": [],
    "body": "Dvicio — Paraíso (179s)",
    "artist": "Dvicio",
    "album": "Paraíso"
  },
  {
    "id": "sp_3401",
    "kind": "music",
    "source": "spotify",
    "title": "Eres una Niña",
    "when": "2015-09-26T02:52:08.000Z",
    "place": "android",
    "people": [],
    "body": "Gerardo Ortiz — Archivos de Mi Vida (170s)",
    "artist": "Gerardo Ortiz",
    "album": "Archivos de Mi Vida"
  },
  {
    "id": "sp_3402",
    "kind": "music",
    "source": "spotify",
    "title": "Dámaso",
    "when": "2015-09-26T02:57:55.000Z",
    "place": "android",
    "people": [],
    "body": "Gerardo Ortiz — El Primer Ministro (Deluxe Edition) (125s)",
    "artist": "Gerardo Ortiz",
    "album": "El Primer Ministro (Deluxe Edition)"
  },
  {
    "id": "sp_3756",
    "kind": "music",
    "source": "spotify",
    "title": "If You Want Blood (You've Got It)",
    "when": "2015-10-28T14:24:10.000Z",
    "place": "android",
    "people": [],
    "body": "AC/DC — Iron Man 2 (274s)",
    "artist": "AC/DC",
    "album": "Iron Man 2"
  },
  {
    "id": "sp_3757",
    "kind": "music",
    "source": "spotify",
    "title": "Shoot to Thrill",
    "when": "2015-10-28T14:27:39.000Z",
    "place": "android",
    "people": [],
    "body": "AC/DC — Back In Black (204s)",
    "artist": "AC/DC",
    "album": "Back In Black"
  },
  {
    "id": "sp_3758",
    "kind": "music",
    "source": "spotify",
    "title": "You Shook Me All Night Long",
    "when": "2015-10-28T14:31:10.000Z",
    "place": "android",
    "people": [],
    "body": "AC/DC — Who Made Who (211s)",
    "artist": "AC/DC",
    "album": "Who Made Who"
  },
  {
    "id": "sp_3759",
    "kind": "music",
    "source": "spotify",
    "title": "Tush - 2012 Collection Remaster",
    "when": "2015-10-28T14:32:58.000Z",
    "place": "android",
    "people": [],
    "body": "ZZ Top — Oh What A Night - 70's Classics (96s)",
    "artist": "ZZ Top",
    "album": "Oh What A Night - 70's Classics"
  },
  {
    "id": "sp_3774",
    "kind": "music",
    "source": "spotify",
    "title": "Walk This Way",
    "when": "2015-10-31T03:54:40.000Z",
    "place": "android",
    "people": [],
    "body": "Aerosmith — Aerosmith's Greatest Hits (211s)",
    "artist": "Aerosmith",
    "album": "Aerosmith's Greatest Hits"
  },
  {
    "id": "sp_3775",
    "kind": "music",
    "source": "spotify",
    "title": "South Bound Saurez - Remaster",
    "when": "2015-10-31T03:58:55.000Z",
    "place": "android",
    "people": [],
    "body": "Led Zeppelin — In Through the out Door (254s)",
    "artist": "Led Zeppelin",
    "album": "In Through the out Door"
  },
  {
    "id": "sp_3776",
    "kind": "music",
    "source": "spotify",
    "title": "Can't You Hear Me Knocking - 2009 Mix",
    "when": "2015-10-31T04:06:11.000Z",
    "place": "android",
    "people": [],
    "body": "The Rolling Stones — Sticky Fingers (436s)",
    "artist": "The Rolling Stones",
    "album": "Sticky Fingers"
  },
  {
    "id": "sp_3777",
    "kind": "music",
    "source": "spotify",
    "title": "Paranoid",
    "when": "2015-10-31T04:09:00.000Z",
    "place": "android",
    "people": [],
    "body": "Black Sabbath — Paranoid (168s)",
    "artist": "Black Sabbath",
    "album": "Paranoid"
  },
  {
    "id": "sp_3778",
    "kind": "music",
    "source": "spotify",
    "title": "Who Are You",
    "when": "2015-10-31T04:15:22.000Z",
    "place": "android",
    "people": [],
    "body": "The Who — Who Are You (382s)",
    "artist": "The Who",
    "album": "Who Are You"
  },
  {
    "id": "sp_4107",
    "kind": "music",
    "source": "spotify",
    "title": "I'm Gonna Catch You",
    "when": "2016-06-06T16:49:52.000Z",
    "place": "android",
    "people": [],
    "body": "The Mud Howlers — R.R.R (63s)",
    "artist": "The Mud Howlers",
    "album": "R.R.R"
  },
  {
    "id": "sp_4108",
    "kind": "music",
    "source": "spotify",
    "title": "Good Times",
    "when": "2016-06-06T17:02:37.000Z",
    "place": "iOS",
    "people": [],
    "body": "The Monkees — Good Times! (166s)",
    "artist": "The Monkees",
    "album": "Good Times!"
  },
  {
    "id": "sp_4109",
    "kind": "music",
    "source": "spotify",
    "title": "You Bring the Summer",
    "when": "2016-06-06T19:20:18.000Z",
    "place": "iOS",
    "people": [],
    "body": "The Monkees — Good Times! (94s)",
    "artist": "The Monkees",
    "album": "Good Times!"
  },
  {
    "id": "sp_4110",
    "kind": "music",
    "source": "spotify",
    "title": "Five Years - 2012 Remaster",
    "when": "2016-06-06T19:25:33.000Z",
    "place": "iOS",
    "people": [],
    "body": "David Bowie — The Rise and Fall of Ziggy Stardust and the Spiders from Mars (280s)",
    "artist": "David Bowie",
    "album": "The Rise and Fall of Ziggy Stardust and the Spiders from Mars"
  },
  {
    "id": "sp_4111",
    "kind": "music",
    "source": "spotify",
    "title": "Soul Love - 2012 Remaster",
    "when": "2016-06-06T19:29:07.000Z",
    "place": "iOS",
    "people": [],
    "body": "David Bowie — The Rise and Fall of Ziggy Stardust and the Spiders from Mars (214s)",
    "artist": "David Bowie",
    "album": "The Rise and Fall of Ziggy Stardust and the Spiders from Mars"
  },
  {
    "id": "sp_4288",
    "kind": "music",
    "source": "spotify",
    "title": "Good Rockin' Tonight",
    "when": "2016-06-11T18:11:17.000Z",
    "place": "android",
    "people": [],
    "body": "Elvis Presley — Elvis At Sun (132s)",
    "artist": "Elvis Presley",
    "album": "Elvis At Sun"
  },
  {
    "id": "sp_4289",
    "kind": "music",
    "source": "spotify",
    "title": "I Forgot To Remember To Forget - 2004 DSD remaster",
    "when": "2016-06-11T18:22:57.000Z",
    "place": "android",
    "people": [],
    "body": "Elvis Presley — Elvis At Sun (148s)",
    "artist": "Elvis Presley",
    "album": "Elvis At Sun"
  },
  {
    "id": "sp_4290",
    "kind": "music",
    "source": "spotify",
    "title": "Tomorrow Night - 2004 DSD remaster",
    "when": "2016-06-11T18:39:20.000Z",
    "place": "android",
    "people": [],
    "body": "Elvis Presley — Elvis At Sun (77s)",
    "artist": "Elvis Presley",
    "album": "Elvis At Sun"
  },
  {
    "id": "sp_4291",
    "kind": "music",
    "source": "spotify",
    "title": "Trying To Get To You - 2004 DSD remaster",
    "when": "2016-06-11T18:41:50.000Z",
    "place": "android",
    "people": [],
    "body": "Elvis Presley — Elvis At Sun (152s)",
    "artist": "Elvis Presley",
    "album": "Elvis At Sun"
  },
  {
    "id": "sp_4292",
    "kind": "music",
    "source": "spotify",
    "title": "I'll Never Let You Go (Little Darlin') - 2004 DSD remaster",
    "when": "2016-06-11T18:44:16.000Z",
    "place": "android",
    "people": [],
    "body": "Elvis Presley — Elvis At Sun (144s)",
    "artist": "Elvis Presley",
    "album": "Elvis At Sun"
  },
  {
    "id": "sp_4476",
    "kind": "music",
    "source": "spotify",
    "title": "Believer",
    "when": "2016-07-06T18:14:27.000Z",
    "place": "iOS",
    "people": [],
    "body": "American Authors — Oh, What A Life (184s)",
    "artist": "American Authors",
    "album": "Oh, What A Life"
  },
  {
    "id": "sp_4477",
    "kind": "music",
    "source": "spotify",
    "title": "Cynical",
    "when": "2016-07-06T18:16:31.000Z",
    "place": "iOS",
    "people": [],
    "body": "blink-182 — California (116s)",
    "artist": "blink-182",
    "album": "California"
  },
  {
    "id": "sp_4478",
    "kind": "music",
    "source": "spotify",
    "title": "Bored To Death",
    "when": "2016-07-06T18:17:50.000Z",
    "place": "iOS",
    "people": [],
    "body": "blink-182 — California (79s)",
    "artist": "blink-182",
    "album": "California"
  },
  {
    "id": "sp_4479",
    "kind": "music",
    "source": "spotify",
    "title": "Burn the Witch",
    "when": "2016-07-06T18:21:30.000Z",
    "place": "iOS",
    "people": [],
    "body": "Radiohead — A Moon Shaped Pool (221s)",
    "artist": "Radiohead",
    "album": "A Moon Shaped Pool"
  },
  {
    "id": "sp_4480",
    "kind": "music",
    "source": "spotify",
    "title": "Daydreaming",
    "when": "2016-07-06T18:27:54.000Z",
    "place": "iOS",
    "people": [],
    "body": "Radiohead — A Moon Shaped Pool (384s)",
    "artist": "Radiohead",
    "album": "A Moon Shaped Pool"
  },
  {
    "id": "sp_4795",
    "kind": "music",
    "source": "spotify",
    "title": "Hallelujah",
    "when": "2016-08-03T18:33:51.000Z",
    "place": "android",
    "people": [],
    "body": "Jeff Buckley — Grace (Legacy Edition) (69s)",
    "artist": "Jeff Buckley",
    "album": "Grace (Legacy Edition)"
  },
  {
    "id": "sp_4796",
    "kind": "music",
    "source": "spotify",
    "title": "The River",
    "when": "2016-08-03T18:37:02.000Z",
    "place": "android",
    "people": [],
    "body": "The Mud Howlers — Timeliness (178s)",
    "artist": "The Mud Howlers",
    "album": "Timeliness"
  },
  {
    "id": "sp_4797",
    "kind": "music",
    "source": "spotify",
    "title": "Time Machine",
    "when": "2016-08-03T18:41:04.000Z",
    "place": "android",
    "people": [],
    "body": "The Mud Howlers — Timeliness (241s)",
    "artist": "The Mud Howlers",
    "album": "Timeliness"
  },
  {
    "id": "sp_4799",
    "kind": "music",
    "source": "spotify",
    "title": "Pecan Tree",
    "when": "2016-08-03T18:45:16.000Z",
    "place": "android",
    "people": [],
    "body": "The Mud Howlers — Timeliness (191s)",
    "artist": "The Mud Howlers",
    "album": "Timeliness"
  },
  {
    "id": "sp_4800",
    "kind": "music",
    "source": "spotify",
    "title": "God - Remastered 2010",
    "when": "2016-08-03T19:29:30.000Z",
    "place": "android",
    "people": [],
    "body": "John Lennon — Plastic Ono Band (253s)",
    "artist": "John Lennon",
    "album": "Plastic Ono Band"
  },
  {
    "id": "sp_4842",
    "kind": "music",
    "source": "spotify",
    "title": "Smooth (feat. Rob Thomas)",
    "when": "2016-08-04T18:57:58.000Z",
    "place": "android",
    "people": [],
    "body": "Santana — Supernatural (64s)",
    "artist": "Santana",
    "album": "Supernatural"
  },
  {
    "id": "sp_4843",
    "kind": "music",
    "source": "spotify",
    "title": "Oye Como Va",
    "when": "2016-08-04T18:59:17.000Z",
    "place": "android",
    "people": [],
    "body": "Santana — Abraxas (79s)",
    "artist": "Santana",
    "album": "Abraxas"
  },
  {
    "id": "sp_4844",
    "kind": "music",
    "source": "spotify",
    "title": "Samba Pa Ti",
    "when": "2016-08-04T19:03:55.000Z",
    "place": "android",
    "people": [],
    "body": "Santana — Abraxas (278s)",
    "artist": "Santana",
    "album": "Abraxas"
  },
  {
    "id": "sp_4845",
    "kind": "music",
    "source": "spotify",
    "title": "Hope You're Feeling Better",
    "when": "2016-08-04T19:05:59.000Z",
    "place": "android",
    "people": [],
    "body": "Santana — Abraxas (123s)",
    "artist": "Santana",
    "album": "Abraxas"
  },
  {
    "id": "sp_4846",
    "kind": "music",
    "source": "spotify",
    "title": "Black Magic Woman / Gypsy Queen",
    "when": "2016-08-04T19:09:07.000Z",
    "place": "android",
    "people": [],
    "body": "Santana — Abraxas (188s)",
    "artist": "Santana",
    "album": "Abraxas"
  },
  {
    "id": "sp_5353",
    "kind": "music",
    "source": "spotify",
    "title": "Sweet Jane - Full Length Version; 2015 Remaster",
    "when": "2016-08-24T01:50:22.000Z",
    "place": "iOS",
    "people": [],
    "body": "The Velvet Underground — Loaded (246s)",
    "artist": "The Velvet Underground",
    "album": "Loaded"
  },
  {
    "id": "sp_5354",
    "kind": "music",
    "source": "spotify",
    "title": "Rock & Roll - Full Length Version; 2015 Remaster",
    "when": "2016-08-24T01:55:05.000Z",
    "place": "iOS",
    "people": [],
    "body": "The Velvet Underground — Loaded (283s)",
    "artist": "The Velvet Underground",
    "album": "Loaded"
  },
  {
    "id": "sp_5355",
    "kind": "music",
    "source": "spotify",
    "title": "Cool It Down - 2015 Remaster",
    "when": "2016-08-24T01:58:10.000Z",
    "place": "iOS",
    "people": [],
    "body": "The Velvet Underground — Loaded (185s)",
    "artist": "The Velvet Underground",
    "album": "Loaded"
  },
  {
    "id": "sp_5356",
    "kind": "music",
    "source": "spotify",
    "title": "New Age - Full Length Version; 2015 Remaster",
    "when": "2016-08-24T02:03:21.000Z",
    "place": "iOS",
    "people": [],
    "body": "The Velvet Underground — Loaded (311s)",
    "artist": "The Velvet Underground",
    "album": "Loaded"
  },
  {
    "id": "sp_5357",
    "kind": "music",
    "source": "spotify",
    "title": "Head Held High - 2015 Remaster",
    "when": "2016-08-24T02:06:17.000Z",
    "place": "iOS",
    "people": [],
    "body": "The Velvet Underground — Loaded (177s)",
    "artist": "The Velvet Underground",
    "album": "Loaded"
  },
  {
    "id": "sp_5519",
    "kind": "music",
    "source": "spotify",
    "title": "A Hard Road",
    "when": "2016-08-29T05:36:52.000Z",
    "place": "windows",
    "people": [],
    "body": "John Mayall & The Bluesbreakers — A Hard Road (189s)",
    "artist": "John Mayall & The Bluesbreakers",
    "album": "A Hard Road"
  },
  {
    "id": "sp_5521",
    "kind": "music",
    "source": "spotify",
    "title": "Mama, Talk To Your Daughter",
    "when": "2016-08-29T05:40:10.000Z",
    "place": "windows",
    "people": [],
    "body": "John Mayall & The Bluesbreakers — A Hard Road (158s)",
    "artist": "John Mayall & The Bluesbreakers",
    "album": "A Hard Road"
  },
  {
    "id": "sp_5522",
    "kind": "music",
    "source": "spotify",
    "title": "Ridin' On The L And N",
    "when": "2016-08-29T05:42:37.000Z",
    "place": "windows",
    "people": [],
    "body": "John Mayall & The Bluesbreakers — A Hard Road (147s)",
    "artist": "John Mayall & The Bluesbreakers",
    "album": "A Hard Road"
  },
  {
    "id": "sp_5523",
    "kind": "music",
    "source": "spotify",
    "title": "All My Life",
    "when": "2016-08-29T05:47:02.000Z",
    "place": "windows",
    "people": [],
    "body": "John Mayall & The Bluesbreakers — A Hard Road (263s)",
    "artist": "John Mayall & The Bluesbreakers",
    "album": "A Hard Road"
  },
  {
    "id": "sp_5524",
    "kind": "music",
    "source": "spotify",
    "title": "Someday After A While (You'll Be Sorry)",
    "when": "2016-08-29T05:50:01.000Z",
    "place": "windows",
    "people": [],
    "body": "John Mayall & The Bluesbreakers — A Hard Road (180s)",
    "artist": "John Mayall & The Bluesbreakers",
    "album": "A Hard Road"
  },
  {
    "id": "sp_5525",
    "kind": "music",
    "source": "spotify",
    "title": "It's Over",
    "when": "2016-08-29T05:52:55.000Z",
    "place": "windows",
    "people": [],
    "body": "John Mayall & The Bluesbreakers — A Hard Road (169s)",
    "artist": "John Mayall & The Bluesbreakers",
    "album": "A Hard Road"
  },
  {
    "id": "sp_5526",
    "kind": "music",
    "source": "spotify",
    "title": "Eagle Eye",
    "when": "2016-08-29T05:55:43.000Z",
    "place": "windows",
    "people": [],
    "body": "John Mayall & The Bluesbreakers — A Hard Road (172s)",
    "artist": "John Mayall & The Bluesbreakers",
    "album": "A Hard Road"
  },
  {
    "id": "sp_5527",
    "kind": "music",
    "source": "spotify",
    "title": "The Stumble",
    "when": "2016-08-29T05:58:36.000Z",
    "place": "windows",
    "people": [],
    "body": "John Mayall & The Bluesbreakers — A Hard Road (172s)",
    "artist": "John Mayall & The Bluesbreakers",
    "album": "A Hard Road"
  },
  {
    "id": "sp_5528",
    "kind": "music",
    "source": "spotify",
    "title": "The Same Way",
    "when": "2016-08-29T06:00:46.000Z",
    "place": "windows",
    "people": [],
    "body": "John Mayall & The Bluesbreakers — A Hard Road (130s)",
    "artist": "John Mayall & The Bluesbreakers",
    "album": "A Hard Road"
  },
  {
    "id": "sp_5529",
    "kind": "music",
    "source": "spotify",
    "title": "Another Kinda Love",
    "when": "2016-08-29T06:03:50.000Z",
    "place": "windows",
    "people": [],
    "body": "John Mayall & The Bluesbreakers — A Hard Road (184s)",
    "artist": "John Mayall & The Bluesbreakers",
    "album": "A Hard Road"
  },
  {
    "id": "sp_5628",
    "kind": "music",
    "source": "spotify",
    "title": "Shine On You Crazy Diamond (Pts. 1-5)",
    "when": "2016-09-04T17:02:17.000Z",
    "place": "android",
    "people": [],
    "body": "Pink Floyd — Wish You Were Here (684s)",
    "artist": "Pink Floyd",
    "album": "Wish You Were Here"
  },
  {
    "id": "sp_5629",
    "kind": "music",
    "source": "spotify",
    "title": "Just Because - Remastered 2010",
    "when": "2016-09-04T17:47:04.000Z",
    "place": "android",
    "people": [],
    "body": "John Lennon — Rock 'N' Roll (46s)",
    "artist": "John Lennon",
    "album": "Rock 'N' Roll"
  },
  {
    "id": "sp_5630",
    "kind": "music",
    "source": "spotify",
    "title": "Have You Heard - Stereo",
    "when": "2016-09-04T18:04:03.000Z",
    "place": "android",
    "people": [],
    "body": "John Mayall & The Bluesbreakers — Bluesbreakers (346s)",
    "artist": "John Mayall & The Bluesbreakers",
    "album": "Bluesbreakers"
  },
  {
    "id": "sp_5631",
    "kind": "music",
    "source": "spotify",
    "title": "Strange Brew",
    "when": "2016-09-04T18:06:49.000Z",
    "place": "android",
    "people": [],
    "body": "Cream — Disraeli Gears (167s)",
    "artist": "Cream",
    "album": "Disraeli Gears"
  },
  {
    "id": "sp_5632",
    "kind": "music",
    "source": "spotify",
    "title": "Sunshine Of Your Love",
    "when": "2016-09-04T18:10:59.000Z",
    "place": "android",
    "people": [],
    "body": "Cream — Disraeli Gears (250s)",
    "artist": "Cream",
    "album": "Disraeli Gears"
  },
  {
    "id": "sp_5689",
    "kind": "music",
    "source": "spotify",
    "title": "Lovers' Eyes",
    "when": "2016-09-07T18:07:18.000Z",
    "place": "iOS",
    "people": [],
    "body": "Mumford & Sons — Babel (232s)",
    "artist": "Mumford & Sons",
    "album": "Babel"
  },
  {
    "id": "sp_5690",
    "kind": "music",
    "source": "spotify",
    "title": "Whispers In The Dark",
    "when": "2016-09-07T18:10:41.000Z",
    "place": "iOS",
    "people": [],
    "body": "Mumford & Sons — Babel (196s)",
    "artist": "Mumford & Sons",
    "album": "Babel"
  },
  {
    "id": "sp_5691",
    "kind": "music",
    "source": "spotify",
    "title": "Not With Haste",
    "when": "2016-09-07T18:20:04.000Z",
    "place": "iOS",
    "people": [],
    "body": "Mumford & Sons — Babel (247s)",
    "artist": "Mumford & Sons",
    "album": "Babel"
  },
  {
    "id": "sp_5692",
    "kind": "music",
    "source": "spotify",
    "title": "Below My Feet",
    "when": "2016-09-07T18:24:58.000Z",
    "place": "iOS",
    "people": [],
    "body": "Mumford & Sons — Babel (292s)",
    "artist": "Mumford & Sons",
    "album": "Babel"
  },
  {
    "id": "sp_5693",
    "kind": "music",
    "source": "spotify",
    "title": "Reminder",
    "when": "2016-09-07T18:32:41.000Z",
    "place": "iOS",
    "people": [],
    "body": "Mumford & Sons — Babel (124s)",
    "artist": "Mumford & Sons",
    "album": "Babel"
  },
  {
    "id": "sp_5876",
    "kind": "music",
    "source": "spotify",
    "title": "Lethargy",
    "when": "2016-09-28T00:41:46.000Z",
    "place": "android",
    "people": [],
    "body": "Bastille — Wild World - Complete Edition (43s)",
    "artist": "Bastille",
    "album": "Wild World - Complete Edition"
  },
  {
    "id": "sp_5877",
    "kind": "music",
    "source": "spotify",
    "title": "Oil On Water",
    "when": "2016-09-28T00:45:15.000Z",
    "place": "android",
    "people": [],
    "body": "Bastille — Wild World - Complete Edition (179s)",
    "artist": "Bastille",
    "album": "Wild World - Complete Edition"
  },
  {
    "id": "sp_5878",
    "kind": "music",
    "source": "spotify",
    "title": "Four Walls (The Ballad Of Perry Smith)",
    "when": "2016-09-28T00:48:58.000Z",
    "place": "android",
    "people": [],
    "body": "Bastille — Wild World - Complete Edition (252s)",
    "artist": "Bastille",
    "album": "Wild World - Complete Edition"
  },
  {
    "id": "sp_5879",
    "kind": "music",
    "source": "spotify",
    "title": "Good Grief",
    "when": "2016-09-28T00:52:25.000Z",
    "place": "android",
    "people": [],
    "body": "Bastille — Wild World - Complete Edition (206s)",
    "artist": "Bastille",
    "album": "Wild World - Complete Edition"
  },
  {
    "id": "sp_5880",
    "kind": "music",
    "source": "spotify",
    "title": "Way Beyond",
    "when": "2016-09-28T02:29:20.000Z",
    "place": "android",
    "people": [],
    "body": "Bastille — Wild World - Complete Edition (91s)",
    "artist": "Bastille",
    "album": "Wild World - Complete Edition"
  },
  {
    "id": "sp_5927",
    "kind": "music",
    "source": "spotify",
    "title": "Houses of the Holy - 1990 Remaster",
    "when": "2016-10-07T19:59:03.000Z",
    "place": "android",
    "people": [],
    "body": "Led Zeppelin — Physical Graffiti (242s)",
    "artist": "Led Zeppelin",
    "album": "Physical Graffiti"
  },
  {
    "id": "sp_5928",
    "kind": "music",
    "source": "spotify",
    "title": "Brown Sugar - Remastered 2009",
    "when": "2016-10-07T20:02:50.000Z",
    "place": "android",
    "people": [],
    "body": "The Rolling Stones — Sticky Fingers (229s)",
    "artist": "The Rolling Stones",
    "album": "Sticky Fingers"
  },
  {
    "id": "sp_5929",
    "kind": "music",
    "source": "spotify",
    "title": "Paradise City",
    "when": "2016-10-07T20:09:42.000Z",
    "place": "android",
    "people": [],
    "body": "Guns N' Roses — Appetite For Destruction (406s)",
    "artist": "Guns N' Roses",
    "album": "Appetite For Destruction"
  },
  {
    "id": "sp_5930",
    "kind": "music",
    "source": "spotify",
    "title": "Slide It In",
    "when": "2016-10-07T20:12:57.000Z",
    "place": "android",
    "people": [],
    "body": "Whitesnake — Whitesnake's Greatest Hits (201s)",
    "artist": "Whitesnake",
    "album": "Whitesnake's Greatest Hits"
  },
  {
    "id": "sp_5931",
    "kind": "music",
    "source": "spotify",
    "title": "Crazy Train",
    "when": "2016-10-07T20:18:30.000Z",
    "place": "android",
    "people": [],
    "body": "Ozzy Osbourne — Blizzard of Ozz (Expanded Edition) (296s)",
    "artist": "Ozzy Osbourne",
    "album": "Blizzard of Ozz (Expanded Edition)"
  },
  {
    "id": "sp_6342",
    "kind": "music",
    "source": "spotify",
    "title": "Sugar",
    "when": "2016-11-28T01:23:07.000Z",
    "place": "windows",
    "people": [],
    "body": "Maroon 5 — V (235s)",
    "artist": "Maroon 5",
    "album": "V"
  },
  {
    "id": "sp_6344",
    "kind": "music",
    "source": "spotify",
    "title": "Heart Of A Girl",
    "when": "2016-11-28T01:31:45.000Z",
    "place": "android",
    "people": [],
    "body": "The Killers — Battle Born (274s)",
    "artist": "The Killers",
    "album": "Battle Born"
  },
  {
    "id": "sp_6345",
    "kind": "music",
    "source": "spotify",
    "title": "Paint the Town Green",
    "when": "2016-11-28T01:39:44.000Z",
    "place": "android",
    "people": [],
    "body": "The Script — No Sound Without Silence (146s)",
    "artist": "The Script",
    "album": "No Sound Without Silence"
  },
  {
    "id": "sp_6346",
    "kind": "music",
    "source": "spotify",
    "title": "The Times They Are A-Changin'",
    "when": "2016-11-28T01:42:55.000Z",
    "place": "android",
    "people": [],
    "body": "Bob Dylan — The Times They Are A-Changin' (192s)",
    "artist": "Bob Dylan",
    "album": "The Times They Are A-Changin'"
  },
  {
    "id": "sp_6347",
    "kind": "music",
    "source": "spotify",
    "title": "Happy Alone",
    "when": "2016-11-28T01:45:18.000Z",
    "place": "android",
    "people": [],
    "body": "Kings of Leon — Youth And Young Manhood (141s)",
    "artist": "Kings of Leon",
    "album": "Youth And Young Manhood"
  },
  {
    "id": "sp_6836",
    "kind": "music",
    "source": "spotify",
    "title": "There She Goes Again",
    "when": "2016-12-07T19:47:08.000Z",
    "place": "android",
    "people": [],
    "body": "The Velvet Underground — The Velvet Underground & Nico 45th Anniversary (63s)",
    "artist": "The Velvet Underground",
    "album": "The Velvet Underground & Nico 45th Anniversary"
  },
  {
    "id": "sp_6837",
    "kind": "music",
    "source": "spotify",
    "title": "Paperback Writer - Remastered 2009",
    "when": "2016-12-07T20:22:11.000Z",
    "place": "android",
    "people": [],
    "body": "The Beatles — Past Masters (139s)",
    "artist": "The Beatles",
    "album": "Past Masters"
  },
  {
    "id": "sp_6838",
    "kind": "music",
    "source": "spotify",
    "title": "The Nazz Are Blue",
    "when": "2016-12-07T20:37:26.000Z",
    "place": "android",
    "people": [],
    "body": "The Yardbirds — Roger The Engineer / Over Under Sideways Down (183s)",
    "artist": "The Yardbirds",
    "album": "Roger The Engineer / Over Under Sideways Down"
  },
  {
    "id": "sp_6839",
    "kind": "music",
    "source": "spotify",
    "title": "Doctor Robert - Remastered 2009",
    "when": "2016-12-07T20:39:45.000Z",
    "place": "android",
    "people": [],
    "body": "The Beatles — Revolver (134s)",
    "artist": "The Beatles",
    "album": "Revolver"
  },
  {
    "id": "sp_6840",
    "kind": "music",
    "source": "spotify",
    "title": "Angie - Remastered",
    "when": "2016-12-07T20:47:53.000Z",
    "place": "android",
    "people": [],
    "body": "The Rolling Stones — Goats Head Soup (273s)",
    "artist": "The Rolling Stones",
    "album": "Goats Head Soup"
  },
  {
    "id": "sp_6855",
    "kind": "music",
    "source": "spotify",
    "title": "I Feel Fine - Remastered 2009",
    "when": "2016-12-08T18:46:27.000Z",
    "place": "android",
    "people": [],
    "body": "The Beatles — Past Masters (80s)",
    "artist": "The Beatles",
    "album": "Past Masters"
  },
  {
    "id": "sp_6856",
    "kind": "music",
    "source": "spotify",
    "title": "Every Little Thing - Remastered 2009",
    "when": "2016-12-08T18:48:41.000Z",
    "place": "android",
    "people": [],
    "body": "The Beatles — Beatles For Sale (124s)",
    "artist": "The Beatles",
    "album": "Beatles For Sale"
  },
  {
    "id": "sp_6857",
    "kind": "music",
    "source": "spotify",
    "title": "Not In That Way",
    "when": "2016-12-08T18:51:59.000Z",
    "place": "android",
    "people": [],
    "body": "Sam Smith — In The Lonely Hour (172s)",
    "artist": "Sam Smith",
    "album": "In The Lonely Hour"
  },
  {
    "id": "sp_6858",
    "kind": "music",
    "source": "spotify",
    "title": "Sgt. Pepper's Lonely Hearts Club Band - Reprise / Remastered 2009",
    "when": "2016-12-08T18:53:12.000Z",
    "place": "android",
    "people": [],
    "body": "The Beatles — Sgt. Pepper's Lonely Hearts Club Band (42s)",
    "artist": "The Beatles",
    "album": "Sgt. Pepper's Lonely Hearts Club Band"
  },
  {
    "id": "sp_6859",
    "kind": "music",
    "source": "spotify",
    "title": "Tomorrow Night - 2004 DSD remaster",
    "when": "2016-12-08T18:55:07.000Z",
    "place": "android",
    "people": [],
    "body": "Elvis Presley — Elvis At Sun (60s)",
    "artist": "Elvis Presley",
    "album": "Elvis At Sun"
  },
  {
    "id": "sp_6949",
    "kind": "music",
    "source": "spotify",
    "title": "Moonage Daydream - 2012 Remaster",
    "when": "2016-12-10T19:42:34.000Z",
    "place": "iOS",
    "people": [],
    "body": "David Bowie — The Rise and Fall of Ziggy Stardust and the Spiders from Mars (181s)",
    "artist": "David Bowie",
    "album": "The Rise and Fall of Ziggy Stardust and the Spiders from Mars"
  },
  {
    "id": "sp_6950",
    "kind": "music",
    "source": "spotify",
    "title": "Flower Of My Heart - Undubbed Version",
    "when": "2016-12-10T19:44:33.000Z",
    "place": "iOS",
    "people": [],
    "body": "Buddy Holly — Down The Line Rarities (39s)",
    "artist": "Buddy Holly",
    "album": "Down The Line Rarities"
  },
  {
    "id": "sp_6951",
    "kind": "music",
    "source": "spotify",
    "title": "I Dreamed a Dream",
    "when": "2016-12-10T19:46:15.000Z",
    "place": "iOS",
    "people": [],
    "body": "Les Misérables-Original London Cast — Les Misérables (Original 1985 London Cast Recording) (100s)",
    "artist": "Les Misérables-Original London Cast",
    "album": "Les Misérables (Original 1985 London Cast Recording)"
  },
  {
    "id": "sp_6952",
    "kind": "music",
    "source": "spotify",
    "title": "I Dreamed a Dream",
    "when": "2016-12-10T19:48:44.000Z",
    "place": "iOS",
    "people": [],
    "body": "Les Misérables - International Cast — Les Misérables: The Complete Symphonic Recording (103s)",
    "artist": "Les Misérables - International Cast",
    "album": "Les Misérables: The Complete Symphonic Recording"
  },
  {
    "id": "sp_6954",
    "kind": "music",
    "source": "spotify",
    "title": "Stars",
    "when": "2016-12-10T19:50:32.000Z",
    "place": "iOS",
    "people": [],
    "body": "Les Misérables - International Cast — Les Misérables: The Complete Symphonic Recording (67s)",
    "artist": "Les Misérables - International Cast",
    "album": "Les Misérables: The Complete Symphonic Recording"
  }
];
  const threads = [
  {
    "id": "t_sess_sp_3003",
    "title": "morning with Macklemore & Ryan Lewis",
    "why": "6 receipts within a 138-minute window on 2015-08-28 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_3003",
      "sp_3005",
      "sp_3006",
      "sp_3008",
      "sp_3009",
      "hh_2162"
    ]
  },
  {
    "id": "t_sess_sp_3397",
    "title": "morning with One Direction",
    "why": "6 receipts within a 15-minute window on 2015-09-26 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_3397",
      "sp_3398",
      "sp_3400",
      "sp_3401",
      "hh_2148",
      "sp_3402"
    ]
  },
  {
    "id": "t_sess_sp_3756",
    "title": "Transportation and music, evening",
    "why": "6 receipts within a 105-minute window on 2015-10-28 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_3756",
      "sp_3757",
      "sp_3758",
      "sp_3759",
      "hh_2123",
      "hh_2122"
    ]
  },
  {
    "id": "t_sess_sp_3774",
    "title": "Transportation and music, morning",
    "why": "6 receipts within a 21-minute window on 2015-10-31 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_3774",
      "hh_2118",
      "sp_3775",
      "sp_3776",
      "sp_3777",
      "sp_3778"
    ]
  },
  {
    "id": "t_sess_sp_4107",
    "title": "Investment and music, late night",
    "why": "6 receipts within a 159-minute window on 2016-06-06 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_4107",
      "sp_4108",
      "hh_1950",
      "sp_4109",
      "sp_4110",
      "sp_4111"
    ]
  },
  {
    "id": "t_sess_sp_4288",
    "title": "Food and music, late night",
    "why": "6 receipts within a 33-minute window on 2016-06-11 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_4288",
      "sp_4289",
      "hh_1946",
      "sp_4290",
      "sp_4291",
      "sp_4292"
    ]
  },
  {
    "id": "t_sess_sp_4476",
    "title": "Investment and music, late night",
    "why": "6 receipts within a 16-minute window on 2016-07-06 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_4476",
      "sp_4477",
      "sp_4478",
      "sp_4479",
      "sp_4480",
      "hh_1927"
    ]
  },
  {
    "id": "t_sess_hh_1916",
    "title": "Family and music, early morning",
    "why": "6 receipts within a 60-minute window on 2016-08-04 (household + spotify).",
    "signals": [
      "time proximity",
      "household + spotify"
    ],
    "receiptIds": [
      "hh_1916",
      "sp_4795",
      "sp_4796",
      "sp_4797",
      "sp_4799",
      "sp_4800"
    ]
  },
  {
    "id": "t_sess_hh_1914",
    "title": "Investment and music, early morning",
    "why": "6 receipts within a 39-minute window on 2016-08-05 (household + spotify).",
    "signals": [
      "time proximity",
      "household + spotify"
    ],
    "receiptIds": [
      "hh_1914",
      "sp_4842",
      "sp_4843",
      "sp_4844",
      "sp_4845",
      "sp_4846"
    ]
  },
  {
    "id": "t_sess_sp_5353",
    "title": "Festivals and music, morning",
    "why": "6 receipts within a 18-minute window on 2016-08-24 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_5353",
      "sp_5354",
      "sp_5355",
      "sp_5356",
      "sp_5357",
      "hh_1901"
    ]
  },
  {
    "id": "t_sess_hh_1900",
    "title": "Household and music, morning",
    "why": "6 receipts within a 32-minute window on 2016-08-29 (household + spotify).",
    "signals": [
      "time proximity",
      "household + spotify"
    ],
    "receiptIds": [
      "hh_1900",
      "sp_5519",
      "sp_5521",
      "sp_5522",
      "sp_5523",
      "sp_5524"
    ]
  },
  {
    "id": "t_sess_sp_5525",
    "title": "Festivals and music, morning",
    "why": "6 receipts within a 19-minute window on 2016-08-29 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_5525",
      "sp_5526",
      "sp_5527",
      "sp_5528",
      "sp_5529",
      "hh_1898"
    ]
  },
  {
    "id": "t_sess_sp_5628",
    "title": "Investment and music, late night",
    "why": "6 receipts within a 88-minute window on 2016-09-04 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_5628",
      "sp_5629",
      "sp_5630",
      "sp_5631",
      "sp_5632",
      "hh_1891"
    ]
  },
  {
    "id": "t_sess_sp_5689",
    "title": "Food and music, late night",
    "why": "6 receipts within a 25-minute window on 2016-09-07 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_5689",
      "sp_5690",
      "sp_5691",
      "sp_5692",
      "hh_1885",
      "sp_5693"
    ]
  },
  {
    "id": "t_sess_sp_5876",
    "title": "morning with Bastille",
    "why": "6 receipts within a 108-minute window on 2016-09-28 (spotify + household).",
    "signals": [
      "time proximity",
      "spotify + household"
    ],
    "receiptIds": [
      "sp_5876",
      "sp_5877",
      "sp_5878",
      "sp_5879",
      "hh_1869",
      "sp_5880"
    ]
  },
  {
    "id": "t_sess_hh_1860",
    "title": "Beauty and music, early morning",
    "why": "6 receipts within a 109-minute window on 2016-10-08 (household + spotify).",
    "signals": [
      "time proximity",
      "household + spotify"
    ],
    "receiptIds": [
      "hh_1860",
      "sp_5927",
      "sp_5928",
      "sp_5929",
      "sp_5930",
      "sp_5931"
    ]
  },
  {
    "id": "t_sess_hh_1783",
    "title": "Food and music, morning",
    "why": "6 receipts within a 58-minute window on 2016-11-28 (household + spotify).",
    "signals": [
      "time proximity",
      "household + spotify"
    ],
    "receiptIds": [
      "hh_1783",
      "sp_6342",
      "sp_6344",
      "sp_6345",
      "sp_6346",
      "sp_6347"
    ]
  },
  {
    "id": "t_sess_hh_1755",
    "title": "Food and music, early morning",
    "why": "6 receipts within a 138-minute window on 2016-12-08 (household + spotify).",
    "signals": [
      "time proximity",
      "household + spotify"
    ],
    "receiptIds": [
      "hh_1755",
      "sp_6836",
      "sp_6837",
      "sp_6838",
      "sp_6839",
      "sp_6840"
    ]
  },
  {
    "id": "t_sess_hh_1754",
    "title": "Subscription and music, early morning",
    "why": "6 receipts within a 25-minute window on 2016-12-09 (household + spotify).",
    "signals": [
      "time proximity",
      "household + spotify"
    ],
    "receiptIds": [
      "hh_1754",
      "sp_6855",
      "sp_6856",
      "sp_6857",
      "sp_6858",
      "sp_6859"
    ]
  },
  {
    "id": "t_sess_hh_1748",
    "title": "early morning with David Bowie",
    "why": "6 receipts within a 81-minute window on 2016-12-11 (household + spotify).",
    "signals": [
      "time proximity",
      "household + spotify"
    ],
    "receiptIds": [
      "hh_1748",
      "sp_6949",
      "sp_6950",
      "sp_6951",
      "sp_6952",
      "sp_6954"
    ]
  }
];
  